# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buscoayuda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=1000)),
                ('correo', models.CharField(max_length=1000)),
                ('trabajador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buscoayuda.Trabajador')),
            ],
        ),
    ]
